# Generated by Django 5.2.6 on 2026-01-14 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
